# All services for the application
services:

  db:
    image: mysql
    container_name: costruire-il-domani-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volume to store database data

  adminer:
    image: adminer
    container_name: costruire-il-domani-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
